// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisCom.Infraestrutura.Data.Context;

namespace SisCom.Infraestrutura.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20211220000801_PessoaFornecedorAjustes01")]
    partial class PessoaFornecedorAjustes01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SisCom.Entidade.Modelos.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36eb9ee0-c33c-4343-b577-d7c75ad615e2"),
                            Codigo = "AC",
                            Nome = "Acre",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("07fd2138-4fa1-4a44-8a88-f9fcabb1c337"),
                            Codigo = "AL",
                            Nome = "Alagoas",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("9a17793f-20c3-4913-ac1f-debb6ed6a769"),
                            Codigo = "AP",
                            Nome = "Amapá",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("071756f7-7fe7-41c8-937f-7abda52ab910"),
                            Codigo = "AM",
                            Nome = "Amazonas",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("2b069935-643d-4607-8f60-27da089b9468"),
                            Codigo = "BA",
                            Nome = "Bahia",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("b9b6b8aa-33e6-44d1-a743-f77ce0ddb110"),
                            Codigo = "CE",
                            Nome = "Ceará",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("724d77eb-bf18-4a93-be1a-11e0812281dd"),
                            Codigo = "DF",
                            Nome = "Distrito Federal",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("f19dd3d4-e581-48ef-809b-0df22f69ca52"),
                            Codigo = "ES",
                            Nome = "Espirito Santo",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("6dc64fd1-d98c-4a4b-9f22-8cbafa558dda"),
                            Codigo = "GO",
                            Nome = "Goias",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("ee5de09d-f8fd-4c4e-af24-b4271ecf87a8"),
                            Codigo = "MA",
                            Nome = "Maranhão",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("639aac23-2cdd-436a-bdee-443f696016d7"),
                            Codigo = "MS",
                            Nome = "Mato Grosso do Sul",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("f7007c11-7d1c-459c-92d6-f2465aa5701a"),
                            Codigo = "MT",
                            Nome = "Mato Grosso",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("ebb939cd-f25f-4b42-9b67-7787de0137c8"),
                            Codigo = "MG",
                            Nome = "Minas Gerais",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("774f0c5b-8775-498c-939f-14f296c9429e"),
                            Codigo = "PA",
                            Nome = "Pará",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("00feb906-b703-4202-8671-bf18280c963e"),
                            Codigo = "PB",
                            Nome = "Paraíba",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("947dd66a-9770-49cc-bfc0-45a26b31208a"),
                            Codigo = "PR",
                            Nome = "Paraná",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("64b55a6c-db7f-4f8b-865f-09b26236c450"),
                            Codigo = "PE",
                            Nome = "Pernambuco",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("7983ad1f-e585-41f0-a312-c02dff92c222"),
                            Codigo = "PI",
                            Nome = "Piauí",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("3d4b9348-d1e0-49b3-b16f-8807edb33fb8"),
                            Codigo = "RJ",
                            Nome = "Rio de Janeiro",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("fcdd9f7e-13db-4feb-9247-ba5dbcc0d6de"),
                            Codigo = "RN",
                            Nome = "Rio Grande do Norte",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("ed68fde0-b24f-40ae-877d-83f773582714"),
                            Codigo = "RS",
                            Nome = "Rio Grande do Sul",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("36f24ccc-3d56-4add-802c-3b559d37ddee"),
                            Codigo = "RO",
                            Nome = "Rondônia",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("a4e56dee-0c96-45dd-8d33-f18a9eff719d"),
                            Codigo = "RR",
                            Nome = "Roraima",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("a25fef73-89ce-4bb6-8871-1bcbbec8ef38"),
                            Codigo = "SC",
                            Nome = "Santa Catarina",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("05595d97-b661-4424-b4c7-2e465ec6bbb6"),
                            Codigo = "SP",
                            Nome = "São Paulo",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("cad20c4a-4e5f-444a-92ca-e8c4fad413dd"),
                            Codigo = "SE",
                            Nome = "Sergipe",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        },
                        new
                        {
                            Id = new Guid("c17cf59f-c344-43cb-87d1-269a5d462b77"),
                            Codigo = "EX",
                            Nome = "Exterior",
                            PaisId = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2")
                        });
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.Fabricante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("NaoVender")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4acbeeac-2d40-4158-b0dd-159ba6cf55a2"),
                            Nome = "Brasil"
                        });
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ_CPF")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("CidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contato")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EMail")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("End_Bairro")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("End_CEP")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("End_Logradouro")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("End_Numero")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FAX")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Fornecedor")
                        .HasColumnType("bit");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomePopular")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PontoReferencia")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Representante")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Site")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.SubGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("SubGrupos");
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.Cidade", b =>
                {
                    b.HasOne("SisCom.Entidade.Modelos.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.Estado", b =>
                {
                    b.HasOne("SisCom.Entidade.Modelos.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.Pessoa", b =>
                {
                    b.HasOne("SisCom.Entidade.Modelos.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("SisCom.Entidade.Modelos.SubGrupo", b =>
                {
                    b.HasOne("SisCom.Entidade.Modelos.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .IsRequired();

                    b.Navigation("Grupo");
                });
#pragma warning restore 612, 618
        }
    }
}
